language: node_js
node_js:
- 10.19.0
cache: npm
install:
- npm ci
script:
- npm test
deploy:
  provider: gae
  keyfile: all-storage-20000-c67b8eddf024.json
  project: all-storage-20000
before_install:
- openssl aes-256-cbc -K $encrypted_c26cef0fbb4e_key -iv $encrypted_c26cef0fbb4e_iv
  -in all-storage-20000-c67b8eddf024.json.enc -out all-storage-20000-c67b8eddf024.json
  -d
